---
# tasks file for builder
- name: install packages
  apt: name={{item}} state=present
  with_items:
    - git
    - default-jre
    - maven

- name: clone repo
  git:
      repo: "{{repo_clone}}"
      dest: "{{repo_dest}}"

