---
# tasks file for prod
- name: Install tomcat9
  apt: 
    name: tomcat9
    state: present
#  notify:
#    - Copy warnik to webapp

- name: Copy warnik to webapp
  synchronize:
    src: "{{warnik_src}}"
    dest: "{{warnik_dest}}"